version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleDebug
      - du -h . | grep app/build/outputs/
      - ls -ltr ./app/build/outputs/apk/
artifacts:
  files:
    - ./app/build/outputs/apk/app-debug.apk
